# Generated by Django 4.1.5 on 2023-03-04 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_kiosco', '0006_alter_purchase_person_delete_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='measure',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
