# Generated by Django 4.1.5 on 2023-03-04 02:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_kiosco', '0007_product_measure'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
